sudo: false

env:
  global:
    - XDEBUG_MODE=coverage

language: php
php:
  - 8.3
  - 8.4

matrix:
  fast_finish: true

before_script:
  - composer install --prefer-dist

script:
  - composer validate
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
