sudo: false

language: php
php:
  - 8.1
  - 8.2
  - 8.3

matrix:
  fast_finish: true

before_script:
  - composer install --prefer-dist

script:
  - composer validate
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
